### ISSUE TITLE
erroe

### ISSUE THREAD

**Issue by aeiousy** [theADAMJR/2PG#9]
there is a error when using the demo in glitch

/rbd/pnpm-volume/e2f90087-0fee-4e19-b4ae-c57ff8312858/node_modules/.registry.npmjs.org/ts-node/8.10.2/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/data/db-wrapper.ts(8,24): error TS1243: 'async' modifier cannot be used with 'abstract' modifier.
    at createTSError (/rbd/pnpm-volume/e2f90087-0fee-4e19-b4ae-c57ff8312858/node_modules/.registry.npmjs.org/ts-node/8.10.2/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/rbd/pnpm-volume/e2f90087-0fee-4e19-b4ae-c57ff8312858/node_modules/.registry.npmjs.org/ts-node/8.10.2/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/rbd/pnpm-volume/e2f90087-0fee-4e19-b4ae-c57ff8312858/node_modules/.registry.npmjs.org/ts-node/8.10.2/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/rbd/pnpm-volume/e2f90087-0fee-4e19-b4ae-c57ff8312858/node_modules/.registry.npmjs.org/ts-node/8.10.2/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/rbd/pnpm-volume/e2f90087-0fee-4e19-b4ae-c57ff8312858/node_modules/.registry.npmjs.org/ts-node/8.10.2/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.require.extensions.<computed> [as .ts] (/rbd/pnpm-volume/e2f90087-0fee-4e19-b4ae-c57ff8312858/node_modules/.registry.npmjs.org/ts-node/8.10.2/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/app/src/data/logs.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Module.m._compile (/rbd/pnpm-volume/e2f90087-0fee-4e19-b4ae-c57ff8312858/node_modules/.registry.npmjs.org/ts-node/8.10.2/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.require.extensions.<computed> [as .ts] (/rbd/pnpm-volume/e2f90087-0fee-4e19-b4ae-c57ff8312858/node_modules/.registry.npmjs.org/ts-node/8.10.2/node_modules/ts-node/src/index.ts:861:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2pg@1.0.0 start:bot: `ts-node src/bot.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 2pg@1.0.0 start:bot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/12.0.0/_logs/2020-11-22T02_28_54_363Z-debug.log

please fix this

**Comment by theADAMJR** [comment]
Should be fixed now 👍
